name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_os_versions: '["jammy", "focal"]'
      enable_macos_checks: true
      # FIXME: https://github.com/swiftlang/github-workflows/pull/140
      # Xcode 16.0 and 16.1 are not actually available
      macos_exclude_xcode_versions: |
        [
          {"xcode_version": "16.0"},
          {"xcode_version": "16.1"},
        ]
      swift_flags: "-Xbuild-tools-swiftc -DSYSTEM_CI"
      enable_linux_static_sdk_build: true
      enable_wasm_sdk_build: true

  build-abi-stable:
    name: Build ABI Stable
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_linux_checks: false
      enable_macos_checks: true
      enable_windows_checks: false
      # Only build
      macos_build_command: "xcrun swift build --build-tests"
      # FIXME: https://github.com/swiftlang/github-workflows/pull/140
      # Xcode 16.0 and 16.1 are not actually available
      macos_exclude_xcode_versions: |
        [
          {"xcode_version": "16.0"},
          {"xcode_version": "16.1"},
        ]
      # Enable availability to match ABI stable verion of system.
      swift_flags: "-Xbuild-tools-swiftc -DSYSTEM_CI -Xbuild-tools-swiftc -DSYSTEM_ABI_STABLE"

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift.org"
      # https://github.com/apple/swift-system/issues/224
      docs_check_enabled: false
      unacceptable_language_check_enabled: false
      license_header_check_enabled: false
      format_check_enabled: false
      python_lint_check_enabled: false
